language: python

# Python releases to test
python:
  - 2.6
  - 2.7

# Django releases
env:
  - DJANGO_VERSION=Django==1.3.7
  - DJANGO_VERSION=Django==1.4.5
  - DJANGO_VERSION=Django==1.5.5
  - DJANGO_VERSION=Django==1.6.1

# Package installation
install:
  - pip install --use-mirrors $DJANGO_VERSION
  - python setup.py install

# Run the tests
script:
  - python setup.py test